version: "3"

services:
  db:
    image: mysql:8.0
    container_name: db
    restart: unless-stopped
    env_file: .env
    environment:
      # env or default
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
        MYSQL_DATABASE: ${MYSQL_DATABASE:-wordpress}
        MYSQL_USER: ${MYSQL_USER:-wordpress}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD:-wordpress}
    labels:
      - traefik.enable=false
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - internal

  wordpress:
    depends_on:
      - db
    image: wordpress:fpm-alpine
    container_name: wordpress
    restart: unless-stopped
    env_file: .env
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: ${MYSQL_USER:-wordpress}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD:-wordpress}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE:-wordpress}
    labels:
      - traefik.enable=false
    volumes:
      - wordpress:/var/www/html
    networks:
      - internal

  webserver:
    depends_on:
      - wordpress
    image: nginx:1.27.4-alpine
    container_name: webserver
    restart: unless-stopped
    volumes:
      - wordpress:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
    networks:
      - internal
      - web

volumes:
  wordpress:
  dbdata:

networks:
  internal:
    external: false
